# Generated by Django 5.0.7 on 2024-08-26 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_todo_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 13, 56, 59, 308466)),
        ),
    ]
